inamika_backoffice_demos:
    path:     /
    defaults: 
        _controller: InamikaBackOfficeBundle:Demos:index
    methods: [GET]
    options:
        breadcrumb:
            label: DEMOS
            parent_route: inamika_backoffice_homepage
            
inamika_backoffice_demos_add:
    path:     /new
    defaults: { _controller: InamikaBackOfficeBundle:Demos:add }
    options:
        breadcrumb:
            label: ADD_DEMO
            parent_route: inamika_backoffice_demos
    methods: [GET]

inamika_backoffice_demos_edit:
    path:     /edit/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Demos:edit }
    methods: [GET]
    options:
        breadcrumb:
            label: EDIT_DEMO
            parent_route: inamika_backoffice_demos

inamika_backoffice_demos_delete:
    path:     /delete/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Demos:delete }
    methods: [POST,DELETE]