api_users:
    resource: "@InamikaApiBundle/Resources/config/users.yml"

api_demos:
    resource: "@InamikaApiBundle/Resources/config/demos.yml"

api_settings:
    resource: "@InamikaApiBundle/Resources/config/settings.yml"

api_lenders:
    resource: "@InamikaApiBundle/Resources/config/lenders.yml"

