api_users:
    path:     /users
    defaults: { _controller: InamikaApiBundle:Users:index }
    methods: [GET]

api_users_get:
    path:     /users/{id}
    defaults: { _controller: InamikaApiBundle:Users:get }
    methods: [GET]

api_users_post:
    path:     /users
    defaults: { _controller: InamikaApiBundle:Users:post }
    methods: [POST]

api_users_put:
    path:     /users/{id}
    defaults: { _controller: InamikaApiBundle:Users:put }
    methods: [PUT]

api_users_delete:
    path:     /users/{id}
    defaults: { _controller: InamikaApiBundle:Users:delete }
    methods: [DELETE]
